### get profile
http://localhost:3001/user/profile
Authorization: Bearer {{$dotenv token}}


### edit profile
POST  http://localhost:3001/user/edit_profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name" : "sajjad kohan new",
    "last_name" : "new-last-name2",
    "skills" : ["nodejs" , "express js"]
}


### get all invite request for user
GET http://localhost:3001/user/inviterequest
Authorization: Bearer {{$dotenv token}}


### get status invite user to team
GET http://localhost:3001/user/getstatus
Authorization: Bearer {{$dotenv token}}
